// import 'jszip';
// import 'pdfmake';
import 'datatables.net-dt';
// import 'datatables.net-buttons-dt';
// import 'datatables.net-buttons/js/buttons.colVis.js';
// import 'datatables.net-buttons/js/buttons.html5.js';
// import 'datatables.net-buttons/js/buttons.print.js';
import 'datatables.net-responsive-dt';
// import 'datatables.net-scroller-dt';
// import 'datatables.net-select-dt';
